### ISSUE TITLE
As vezes a API não retorna resultados das requisições

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#153]
### Descrição
As vezes as requisições são retornadas nulas. Porém logo após, se fizer outra requisição (ou dar refresh na página) os resultados são retornados normalmente. Isso faz os testes automatizados não passarem e consequentemente a build falhar

### Critérios de Aceitação
- [ ] Todas requisições são retornadas normalmente sem erros.

### Tarefas
- [ ] Tratar exceção para que quando a requisição retornar nula, refazer outra requisição automaticamente

**Comment by daluzguilherme** [comment]
Segue o log do terminal do Travis:

```
======================================================================
ERROR: test_get_contributors_login (pygithub_api_integration.tests.RepoInfoTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/pygithub_api_integration/tests.py", line 36, in test_get_contributors_login
    response = self.make_client_request(RepoInfoTests.url_name)
  File "/code/test_utils/setup_test_cases.py", line 17, in make_client_request
    response = self.client.post(url, content)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 525, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 341, in post
    secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 404, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 485, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/pygithub_api_integration/views.py", line 24, in getRepoInfo
    Contributor.saveContributors(contributors_request, repo)
  File "/code/pygithub_api_integration/models.py", line 57, in saveContributors
    for c in contributors_request:
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 10 tests in 7.188s
```

**Comment by Mateusas3s** [comment]
Exceção criada para essa falha
